---
Logging:
  LogLevel: debug

Lora:
  Module: sx1262
  DIO2_AS_RF_SWITCH: true
  CS: 21
  IRQ: 16
  Busy: 20
  Reset: 18
  spidev: spidev0.0

GPS:
#  SerialPath: /dev/ttyS0

Webserver:
  Port: 443
  RootPath: /home/ch/src/meshtastic-native/node/web

General:
  MaxNodes: 200
  MaxMessageQueue: 100
